apps/urls.py
from django.contrib.auth.views import LoginView
from django.urls import path

from apps.views import ProductListView, RegisterCreateView, LogoutView, VerifyEmailConfirm, \
    ProductDetailView, UserProfileTemplateView, UserSettingsUpdateView

urlpatterns = [

    # path('', MainTemplateView.as_view(), name='main_page'),
    path('', ProductListView.as_view(), name='product_list_page'),
    path('product-detail/<int:pk>', ProductDetailView.as_view(), name='product_detail_page'),
    path('login', LoginView.as_view(template_name='apps/auth/login/login_page.html',
                                    redirect_authenticated_user=True,
                                    next_page='product_list_page'), name='login_page'),
    path('logout', LogoutView.as_view(), name="logout_page"),
    path('user-profile', UserProfileTemplateView.as_view(), name="user_profile_page"),
    path('user-settings', UserSettingsUpdateView.as_view(), name="user_settings_page"),
    path('user-update-photo', UserSettingsUpdateView.as_view(), name="user_update_photo_page"),
    path('register', RegisterCreateView.as_view(), name='register_page'),
    path('verify-email-confirm/<uidb64>/<token>/', VerifyEmailConfirm.as_view(), name='verify-email-confirm'),

]

# path('email', send_message_to_email, name='email_page')
# path('verify-email/', VerifyEmail.as_view(), name='verify-email'),
# path('verify-email/done/', VerifyEmailDone.as_view(), name='verify-email-done'),
# path('verify-email/complete/', VerifyEmailComplete.as_view(), name='verify-email-complete'),

root/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from root.settings import MEDIA_URL, MEDIA_ROOT, STATIC_URL, STATIC_ROOT

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('apps.urls')),
                  path("ckeditor5/", include('django_ckeditor_5.urls'))
              ] + static(MEDIA_URL, document_root=MEDIA_ROOT) + static(STATIC_URL, document_root=STATIC_ROOT)

apps/models/products.py
import string

from django.core.validators import FileExtensionValidator
from django.db.models import Model, CharField, DateTimeField, JSONField, CASCADE, ForeignKey, ImageField, BooleanField, \
    ManyToManyField, PositiveIntegerField, IntegerField, \
    SmallIntegerField, TextField, SlugField
from django.db.models import Q, CheckConstraint
from django.db.models.functions import Now
from django.utils.text import slugify
from django_ckeditor_5.fields import CKEditor5Field
from mptt.fields import TreeForeignKey
from mptt.models import MPTTModel


class Category(MPTTModel):
    name = CharField(max_length=50, unique=True)
    slug = SlugField(editable=False)
    parent = TreeForeignKey('self', CASCADE, null=True, blank=True, related_name='children')

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        self.slug = slugify(self.name)
        while self.__class__.objects.filter(slug=self.slug).exists():
            letters = string.ascii_lowercase
            self.slug += f"{len(Category.objects.all())}"  # 2 - logic
        super().save(force_insert, force_update, using, update_fields)

    class MPTTMeta:
        order_insertion_by = ['name']

    class Meta:
        db_table = 'category'

    def __str__(self):
        return self.name


class Product(Model):
    name = CharField(max_length=255)
    author = ForeignKey('apps.User', CASCADE)
    price = IntegerField(verbose_name='Price', help_text="Price of product in $")
    shipping_cost = IntegerField(verbose_name='Shipping cost', default=50, help_text="Pay for delivery $")
    discount = IntegerField(verbose_name='Discount', default=0, help_text="discount in % ")
    stock = BooleanField(verbose_name="Is exists", default=False)
    quantity = IntegerField(verbose_name='Amount', default=0)
    properties = JSONField(verbose_name='Properties', blank=True, default=dict)
    description = CKEditor5Field(verbose_name='Description', null=True, blank=True)
    category = ForeignKey('apps.Category', on_delete=CASCADE)
    tags = ManyToManyField('apps.Tag', blank=True)
    updated_at = DateTimeField(verbose_name='Updated at', auto_now_add=True, db_default=Now())
    created_at = DateTimeField(verbose_name='Created at', auto_now=True, db_default=Now())

    @property
    def current_price(self):
        return self.price - (self.price * self.discount) // 100

    class Meta:
        db_table = 'product'


class ProductImage(Model):
    photo = ImageField(upload_to='products/%Y/%m/%d/',
                       validators=[FileExtensionValidator(['png', 'jpeg', 'jpg', 'webp'])])
    product = ForeignKey('apps.Product', CASCADE, related_name='images')
    updated_at = DateTimeField(auto_now_add=True, db_default=Now())
    created_at = DateTimeField(auto_now=True, db_default=Now())

    def delete(self, using=None, keep_parents=False):
        self.photo.delete(False)
        return super().delete(using, keep_parents)

    class Meta:
        db_table = 'productimage'


class Tag(Model):
    name = CharField(max_length=255)

    class Meta:
        db_table = 'tag'

    def __str__(self):
        return self.name


class Review(Model):
    review_text = TextField(null=True, blank=True)
    review_title = CharField(max_length=255, null=True, blank=True)
    product = ForeignKey('apps.Product', on_delete=CASCADE)
    author = ForeignKey('apps.User', on_delete=CASCADE)
    rating = SmallIntegerField(default=0)
    created_at = DateTimeField(auto_now_add=True)

    class Meta:
        constraints = [
            CheckConstraint(check=Q(rating__gte=0) & Q(rating__lte=10), name="rating_between_0_and_10"),
        ]

        db_table = 'review'


class Order(Model):
    user = ForeignKey('apps.User', on_delete=CASCADE)
    created_at = DateTimeField(auto_now_add=True)

    class Meta:
        db_table = 'order'


class Cart(Model):
    user = ForeignKey('apps.User', on_delete=CASCADE)
    product = ForeignKey('apps.Product', on_delete=CASCADE, related_name='product_id')
    created_at = DateTimeField(auto_now_add=True)

    class Meta:
        db_table = 'cart'


class OrderItem(Model):
    order = ForeignKey('apps.Order', on_delete=CASCADE)
    quantity = PositiveIntegerField(default=1, db_default=1)

    class Meta:
        db_table = 'orderitem'


class Region(Model):
    name = CharField(max_length=255)

    class Meta:
        db_table = 'region'


class District(Model):
    name = CharField(max_length=255)
    region = ForeignKey('apps.Region', CASCADE)

    class Meta:
        db_table = 'district'


class Country(Model):
    name = CharField(max_length=255)
    code = CharField(max_length=5)

    class Meta:
        db_table = 'country'

templates/apps/product/product_detail.html
{% extends 'apps/base.html' %}

{% load static %}

{% block title %}
    Product Detail
{% endblock %}

{% block main_content %}

    <div class="card mb-3">
        <div class="card-body">
            <div class="row">
                <div class="col-lg-6 mb-4 mb-lg-0">
                    <div class="product-slider" id="galleryTop">
                        <div class="swiper-container theme-slider position-lg-absolute all-0"
                             data-swiper='{"autoHeight":true,"spaceBetween":5,"loop":true,"loopedSlides":5,"thumb":{"spaceBetween":5,"slidesPerView":5,"loop":true,"freeMode":true,"grabCursor":true,"loopedSlides":5,"centeredSlides":true,"slideToClickedSlide":true,"watchSlidesVisibility":true,"watchSlidesProgress":true,"parent":"#galleryTop"},"slideToClickedSlide":true}'>
                            {#                            <div class="swiper-wrapper h-100">#}
                            {#                                {% for p in product.images.all %}#}
                            {#                                    <div class="swiper-slide h-100"><img class="rounded-1 fit-cover h-100 w-100"#}
                            {#                                                                         src="{{ p.photo.url }}"#}
                            {#                                                                         alt=""/></div>#}
                            {#                                {% endfor %}#}
                            {##}
                            {#                            </div>#}
                            <div class="swiper-nav">
                                <div class="swiper-button-next swiper-button-white"></div>
                                <div class="swiper-button-prev swiper-button-white"></div>
                            </div>
                        </div>
                        <div>
                            <img class="rounded-1 fit-cover h-100 w-100"
                                 src="{{ product.images.first.photo.url }}"
                                 alt=""/>
                        </div>
                    </div>
                </div>
                <div class="col-lg-6">
                    <h5>
                        {{ product.description|striptags }}
                    </h5>
                    <a class="fs--1 mb-2 d-block" href="#!">Computer
                        &amp; Accessories
                    </a>
                    <div class="fs--2 mb-3 d-inline-block text-decoration-none"><span
                            class="fa fa-star text-warning"></span><span class="fa fa-star text-warning"></span><span
                            class="fa fa-star text-warning"></span><span class="fa fa-star text-warning"></span><span
                            class="fa fa-star-half-alt text-warning star-icon"></span><span
                            class="ms-1 text-600">(8)</span>
                    </div>
                    <p class="fs--1">{{ product.description|striptags }}</p>
                    <h4 class="d-flex align-items-center"><span
                            class="text-warning me-2">${{ product.current_price }}</span><span
                            class="me-1 fs--1 text-500">
                      <del class="me-1">${{ product.price }}</del><strong>-{{ product.discount }}%</strong></span></h4>
                    <p class="fs--1 mb-1"><span>Shipping Cost: </span><strong>${{ product.shipping_cost }}</strong></p>
                    {% if product.stock %}
                        <p class="fs--1">Stock: <strong class="text-success">Available</strong></p>
                    {% else %}
                        <p class="fs--1">Stock: <strong class="text-danger">Sold-out</strong></p>
                    {% endif %}


                    <p class="fs--1 mb-3">Tags: <a class="ms-2" href="#!">Computer,</a><a class="ms-1"
                                                                                          href="#!">Mac
                        Book,</a><a class="ms-1" href="#!">Mac Book Pro,</a><a class="ms-1"
                                                                               href="#!">Laptop </a></p>
                    <div class="row">
                        <div class="col-auto pe-0">
                            <div class="input-group input-group-sm" data-quantity="data-quantity">
                                <button class="btn btn-sm btn-outline-secondary border-300"
                                        data-field="input-quantity" data-type="minus">-
                                </button>
                                <input class="form-control text-center input-quantity input-spin-none"
                                       type="number" min="0" value="0"
                                       aria-label="Amount (to the nearest dollar)" style="max-width: 50px"/>
                                <button class="btn btn-sm btn-outline-secondary border-300"
                                        data-field="input-quantity" data-type="plus">+
                                </button>
                            </div>
                        </div>
                        <div class="col-auto px-2 px-md-3"><a class="btn btn-sm btn-primary" href="#!"><span
                                class="fas fa-cart-plus me-sm-2"></span><span
                                class="d-none d-sm-inline-block">Add To Cart</span></a>
                        </div>
                        <div class="col-auto px-0"><a class="btn btn-sm btn-outline-danger border-300" href="#!"
                                                      data-bs-toggle="tooltip" data-bs-placement="top"
                                                      title="Add to Wish List"><span
                                class="far fa-heart me-1"></span>282</a></div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-12">
                    <div class="overflow-hidden mt-4">
                        <ul class="nav nav-tabs" id="myTab" role="tablist">
                            <li class="nav-item"><a class="nav-link active ps-0" id="description-tab"
                                                    data-bs-toggle="tab" href="#tab-description" role="tab"
                                                    aria-controls="tab-description" aria-selected="true">Description</a>
                            </li>
                            <li class="nav-item"><a class="nav-link px-2 px-md-3" id="specifications-tab"
                                                    data-bs-toggle="tab" href="#tab-specifications" role="tab"
                                                    aria-controls="tab-specifications"
                                                    aria-selected="false">Specifications</a>
                            </li>
                            <li class="nav-item"><a class="nav-link px-2 px-md-3" id="reviews-tab"
                                                    data-bs-toggle="tab" href="#tab-reviews" role="tab"
                                                    aria-controls="tab-reviews"
                                                    aria-selected="false">Reviews</a></li>
                        </ul>
                        <div class="tab-content" id="myTabContent">
                            <div class="tab-pane fade show active" id="tab-description" role="tabpanel"
                                 aria-labelledby="description-tab">
                                <div class="mt-3">
                                    <p>{{ product.description|striptags }}</p>
                                </div>
                            </div>
                            <div class="tab-pane fade" id="tab-specifications" role="tabpanel"
                                 aria-labelledby="specifications-tab">
                                <table class="table fs--1 mt-3">
                                    <tbody>
                                    {% for key, value in product.properties.items %}
                                        <tr>
                                            <td class="bg-100" style="width: 30%;">{{ key }}</td>
                                            <td>{{ value }},</td>
                                        </tr>
                                    {% endfor %}

                                    </tbody>
                                </table>
                            </div>
                            <div class="tab-pane fade" id="tab-reviews" role="tabpanel"
                                 aria-labelledby="reviews-tab">
                                <div class="row mt-3">
                                    <div class="col-lg-6 mb-4 mb-lg-0">

                                        <div class='DivToScroll'>
                                            <div class="DivWithScroll">
                                                {% for review in product.review_set.all %}
                                                    <div class="mb-1"><span
                                                            class="fa fa-star text-warning fs--1"></span><span
                                                            class="fa fa-star text-warning fs--1"></span><span
                                                            class="fa fa-star text-warning fs--1"></span><span
                                                            class="fa fa-star text-warning fs--1"></span><span
                                                            class="fa fa-star text-warning fs--1"></span><span
                                                            class="ms-3 text-dark fw-semi-bold">{{ review.review_title }}</span>
                                                    </div>
                                                    <p class="fs--1 mb-2 text-600">By {{ user.first_name }}
                                                        • {{ review.created_at|date:'M d Y' }} </p>
                                                    <p class="mb-0">{{ review.review_text }}.</p>
                                                    <hr class="my-4"/>
                                                {% endfor %}
                                            </div>
                                        </div>


                                    </div>
                                    <div class="col-lg-6 ps-lg-5">
                                        <form action='{% url 'product_detail_page' product.pk %}' method="post">
                                            {% csrf_token %}
                                            <h5 class="mb-3">Write your Review</h5>
                                            <div class="mb-3">
                                                <label class="form-label">Ratting: </label>
                                                <div class="d-block"
                                                     data-rater='{"starSize":32,"step":0.5}'></div>
                                            </div>
                                            <div class="mb-3">
                                                <label class="form-label" for="formGroupNameInput">Name:</label>
                                                <input class="form-control" name="review_title" id="formGroupNameInput"
                                                       type="text"/>
                                            </div>
                                            <div class="mb-3">
                                                <label class="form-label"
                                                       for="formGrouptextareaInput">Review:</label>
                                                <textarea class="form-control" name="review_text"
                                                          id="formGrouptextareaInput"
                                                          rows="3"></textarea>
                                            </div>

                                            <input class="form-control" name="author_id" id="formGroupEmailInput"
                                                   type="hidden" value="{{ user.pk }}"/>
                                            <input class="form-control" name="product_id" id="formGroupEmailInput"
                                                   type="hidden" value="{{ product.pk }}"/>


                                            <button class="btn btn-primary" type="submit">Submit</button>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/apps/product/product_list.html
{% extends 'apps/base.html' %}
{% load custom_tags %}
{% block title %}
    Products List
{% endblock %}

{% block main_content %}

    <div class="card mb-3">
        <div class="card-body">
            <div class="row flex-between-center">
                <div class="col-sm-auto mb-2 mb-sm-0">
                    <h6 class="mb-0">Showing {{ page_obj.start_index }}-{{ page_obj.end_index }}
                        of {{ page_obj.paginator.count }} Products</h6>
                </div>
                <div class="col-sm-auto">
                    <div class="row gx-2 align-items-center">
                        <div class="col-auto">
                            <form class="row gx-2">
                                <div class="col-auto"><small>Sort by: </small></div>
                                <div class="col-auto">
                                    <select class="form-select form-select-sm" aria-label="Bulk actions">
                                        <option selected="">Best Match</option>
                                        <option value="Refund">Newest</option>
                                        <option value="Delete">Price</option>
                                    </select>
                                </div>
                            </form>
                        </div>
                        <div class="col-auto pe-0"><a class="text-600 px-1"
                                                      href="../../../app/e-commerce/product/product-grid.html"
                                                      data-bs-toggle="tooltip" title="Product Grid"><span
                                class="fas fa-th"></span></a></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="card">
        <div class="card-body p-0 overflow-hidden">
            <div class="row g-0">
                {% for product in products %}
                    <div class="col-12 p-card">
                        <div class="row">
                            <div class="col-sm-5 col-md-4">
                                <div class="position-relative h-sm-100">
                                    <a class="d-block h-100"
                                       hreflang=""
                                       href="{% url 'product_detail_page' product.pk %}">
                                        <img class="img-fluid fit-cover w-sm-100 h-sm-100 rounded-1 absolute-sm-centered"
                                             src="{{ product.images.first.photo.url }}" alt=""/>
                                    </a>
                                    {% now "Y" as current_year %}
                                    {% if product.created_at|is_new %}
                                        <div class="badge rounded-pill bg-success position-absolute top-0 end-0 me-2 mt-2 fs--2 z-index-2">
                                            New
                                        </div>
                                    {% endif %}
                                </div>
                            </div>
                            <div class="col-sm-7 col-md-8">
                                <div class="row">
                                    <div class="col-lg-8">
                                        <h5 class="mt-3 mt-sm-0"><a class="text-dark fs-0 fs-lg-1"
                                                                    href="{% url 'product_detail_page' product.pk %}">{{ product.description|striptags }}</a>
                                        </h5>
                                        <p class="fs--1 mb-2 mb-md-3"><a class="text-500" href="{% url 'product_list_page' %}?category={{ product.category.slug }}">{{ product.category.name }}</a></p>
                                        <ul class="list-unstyled d-none d-lg-block">
                                            {% for key, value in product.properties.items %}
                                                <li><span class="fas fa-circle"
                                                          data-fa-transform="shrink-12"></span>
                                                    <span>{{ key }} {{ value }} </span>
                                                </li>
                                            {% endfor %}
                                        </ul>
                                    </div>
                                    <div class="col-lg-4 d-flex justify-content-between flex-column">
                                        <div>
                                            {% if product.discount %}
                                                <h4 class="fs-1 fs-md-2 text-warning mb-0">
                                                    ${{ product.current_price }}</h4>
                                                <h5 class="fs--1 text-500 mb-0 mt-1">
                                                    <del>${{ product.price }}</del>
                                                    <span class="ms-1">-{{ product.discount }}%</span>
                                                </h5>
                                            {% else %}
                                                <h4 class="fs-1 fs-md-2 text-warning mb-0">${{ product.price }}</h4>
                                            {% endif %}
                                            <div class="mb-2 mt-3"><span
                                                    class="fa fa-star text-warning"></span><span
                                                    class="fa fa-star text-warning"></span><span
                                                    class="fa fa-star text-warning"></span><span
                                                    class="fa fa-star text-warning"></span><span
                                                    class="fa fa-star text-300"></span><span class="ms-1">(8)</span>
                                            </div>
                                            <div class="d-none d-lg-block">
                                                <p class="fs--1 mb-1">Shipping Cost:
                                                    <strong>${{ product.shipping_cost }}</strong></p>
                                                {% if product.quantity %}
                                                    <p class="fs--1 mb-1">Stock: <strong
                                                            class="text-success">Available</strong>
                                                    </p>
                                                {% else %}
                                                    <p class="fs--1 mb-1">Stock: <strong
                                                            class="text-danger">Sold-Out</strong>
                                                    </p>
                                                {% endif %}

                                            </div>
                                        </div>
                                        <div class="mt-2"><a
                                                class="btn btn-sm btn-outline-secondary border-300 d-lg-block me-2 me-lg-0"
                                                href="#!"><span class="far fa-heart"></span><span
                                                class="ms-2 d-none d-md-inline-block">Favourite</span></a><a
                                                class="btn btn-sm btn-primary d-lg-block mt-lg-2" href="#!"><span
                                                class="fas fa-cart-plus"> </span><span
                                                class="ms-2 d-none d-md-inline-block">Add to Cart</span></a></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
        <div class="card-footer border-top d-flex justify-content-center">
            {% if not page_obj.has_previous %}
                <button class="btn btn-falcon-default btn-sm" disabled="disabled" id="DataTables_Table_0_next"><a
                        href="?page={{ page_obj.number }}" aria-controls="DataTables_Table_0"
                        data-dt-idx="3"
                        tabindex="0" class="page-link">
                    <
                </a>

                </button>
            {% else %}
                <button class="btn btn-falcon-default btn-sm" id="DataTables_Table_0_next">
                    <a href="?page={{ page_obj.previous_page_number }}" aria-controls="DataTables_Table_0"
                       data-dt-idx="3" tabindex="0" class="page-link">
                        <
                    </a>
                </button>
            {% endif %}

            <a class="btn btn-sm btn-falcon-default text-primary me-2" href="#">
                {{ page_obj.number }}
            </a>
            {% if page_obj.has_next and page_obj.next_page_number != page_obj.paginator.num_pages %}
                <a class="btn btn-sm btn-falcon-default me-2" href="?page={{ page_obj.next_page_number }}">
                    {{ page_obj.next_page_number }}
                </a>
            {% endif %}
            {% if not page_obj.has_next %}
                <button class="btn btn-falcon-default btn-sm" disabled="disabled" id="DataTables_Table_0_next"><a
                        href="#" aria-controls="DataTables_Table_0"
                        data-dt-idx="3"
                        tabindex="0" class="page-link">
                    >
                </a>
                </button>
            {% else %}
                <a class="btn btn-sm btn-falcon-default me-2" href="#!"><span class="fas fa-ellipsis-h"></span></a>
                <a class="btn btn-sm btn-falcon-default me-2" href="#">
                    {{ page_obj.paginator.num_pages }}
                </a>
                <button class="btn btn-falcon-default btn-sm" id="DataTables_Table_0_next"><a
                        href="?page={{ page_obj.next_page_number }}" aria-controls="DataTables_Table_0"
                        data-dt-idx="3"
                        tabindex="0" class="page-link">
                    >
                </a>
                </button>
            {% endif %}
        </div>
    </div>

{% endblock %}